/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JProgressBar;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author hp
 */
public class VistaMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenuPrincipal
     */
    public VistaMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEstado = new javax.swing.JLabel();
        prgGeneral = new javax.swing.JProgressBar();
        dskPrincipal = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        tblClientes = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        tblProductos = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        tblFactura = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuProductos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuFactura = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEstado.setText("Tienda 1.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEstado)
                .addGap(141, 141, 141)
                .addComponent(prgGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prgGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dskPrincipalLayout = new javax.swing.GroupLayout(dskPrincipal);
        dskPrincipal.setLayout(dskPrincipalLayout);
        dskPrincipalLayout.setHorizontalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dskPrincipalLayout.setVerticalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );

        jToolBar1.setRollover(true);

        tblClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mvc/vista/iconos/analytics.png"))); // NOI18N
        tblClientes.setToolTipText("Persona");
        tblClientes.setFocusable(false);
        tblClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tblClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tblClientes);
        jToolBar1.add(jSeparator2);

        tblProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mvc/vista/iconos/analytics.png"))); // NOI18N
        tblProductos.setToolTipText("Productos");
        tblProductos.setFocusable(false);
        tblProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tblProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tblProductos);
        jToolBar1.add(jSeparator4);

        tblFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mvc/vista/iconos/analytics.png"))); // NOI18N
        tblFactura.setFocusable(false);
        tblFactura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tblFactura.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tblFactura);

        jMenu1.setText("Cliente");

        mnuClientes.setText(" Mantenimiento");
        jMenu1.add(mnuClientes);

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        mnuSalir.setText("Salir");
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Producto");

        mnuProductos.setText("Mantenimiento");
        jMenu2.add(mnuProductos);

        jMenuItem1.setText("jMenuItem1");
        jMenu2.add(jMenuItem1);
        jMenu2.add(jSeparator3);

        jMenuItem3.setText("Salir");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Factura");

        mnuFactura.setText("Mantenimiento");
        jMenu3.add(mnuFactura);
        jMenu3.add(jSeparator5);

        jMenuItem5.setText("Salir");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ayuda");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dskPrincipal)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dskPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaMenuPrincipal().setVisible(true);
//            }
//        });
//    }

    public JDesktopPane getDskPrincipal() {
        return dskPrincipal;
    }

    public void setDskPrincipal(JDesktopPane dskPrincipal) {
        this.dskPrincipal = dskPrincipal;
    }

    public JLabel getLblEstado() {
        return lblEstado;
    }

    public void setLblEstado(JLabel lblEstado) {
        this.lblEstado = lblEstado;
    }

    public JMenuItem getMnuClientes() {
        return mnuClientes;
    }

    public void setMnuClientes(JMenuItem mnuClientes) {
        this.mnuClientes = mnuClientes;
    }

    public JMenuItem getMnuSalir() {
        return mnuSalir;
    }

    public void setMnuSalir(JMenuItem mnuSalir) {
        this.mnuSalir = mnuSalir;
    }

    public JProgressBar getPrgGeneral() {
        return prgGeneral;
    }

    public void setPrgGeneral(JProgressBar prgGeneral) {
        this.prgGeneral = prgGeneral;
    }

    public JButton getTblClientes() {
        return tblClientes;
    }

    public void setTblClientes(JButton tblClientes) {
        this.tblClientes = tblClientes;
    }

    public JMenuItem getMnuProductos() {
        return mnuProductos;
    }

    public void setMnuProductos(JMenuItem mnuProductos) {
        this.mnuProductos = mnuProductos;
    }

    public JButton getTblProductos() {
        return tblProductos;
    }

    public void setTblProductos(JButton tblProductos) {
        this.tblProductos = tblProductos;
    }

    public JMenuItem getMnuFactura() {
        return mnuFactura;
    }

    public void setMnuFactura(JMenuItem mnuFactura) {
        this.mnuFactura = mnuFactura;
    }

    public JButton getTblFactura() {
        return tblFactura;
    }

    public void setTblFactura(JButton tblFactura) {
        this.tblFactura = tblFactura;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskPrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuFactura;
    private javax.swing.JMenuItem mnuProductos;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JProgressBar prgGeneral;
    private javax.swing.JButton tblClientes;
    private javax.swing.JButton tblFactura;
    private javax.swing.JButton tblProductos;
    // End of variables declaration//GEN-END:variables
}
